# Requieres a list of [update_server] in a hosts file.
# ansible-playbook -i hosts playbooks/update_server.yml --ask-become-pass
---
- name: Update all Debian servers
  hosts: update_server
  become: true
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
